state_dir: ~/.lightbeam/
data_dir: example/
validate: True
swagger: https://api.ed-fi.org/v5.3/api/metadata/data/v3/resources/swagger.json
edfi_api:
  base_url: https://localhost/api
  version: 3
  mode: year_specific
  year: 2021
  client_id: populated
  client_secret: populatedSecret
connection:
  pool_size: 8 # simultaneous connections
  timeout: 60 # seconds
  num_retries: 10
  retry_statuses: [429, 500, 501, 503, 504]
  backoff_factor: 1.5
  verify_ssl: False
verbose: False
show_stacktrace: False