state_dir: ~/.lightbeam/
data_dir: example/
edfi_api:
  base_url: https://localhost/api
  verify_ssl: False
  version: 3
  mode: year_specific
  year: 2021
  client_id: populated
  client_secret: populatedSecret
connection:
  pool_size: 8 # simultantous connections
  timeout: 60 # seconds
  num_retries: 10
  retry_statuses: [429, 500, 501, 503, 504]
  backoff_factor: 1.5
verbose: True
show_stacktrace: True